### ISSUE TITLE
Agnostic?

### ISSUE THREAD

**Issue by KarelWintersky** [Jagepard/Rudra-Router#93]
Насколько оно agnostic? Может работать без остального фреймворка?

**Comment by Jagepard** [comment]
Да, работает

**Comment by Jagepard** [comment]
agnostic - переводится вроде как непознаваемое, первый раз встречаю слово в таком смысле)))

**Comment by KarelWintersky** [comment]
Я agnostic в плане пакетов встречал именно в контексте "Требует для работы зоопарк" или "может работать само по себе". Framework-less звучит намного хуже (хотя и понятнее). 

А что под капотом роутера? nikic/fast-route или своё?

**Comment by Jagepard** [comment]
Про agnostic понял, буду иметь в виду. Под капотом 100% самодельный, как и все части фреймворка. Просто было желание написать фреймворк с чистого листа, чтобы лучше понимать принципы работы других (под капотом)

А так думаю FastRoute или Aura.Router будут хорошими вариантами.
Мой все-таки больше любительский проект, использую только для себя.

**Comment by KarelWintersky** [comment]
В Fastrouter "искаропки" нет миддлварей и не очень удобно все инстанциируется. 

А Aura просто крайне многословная:
```
$map->get('blog.read', '/blog/{id}{format}')
    ->tokens([
        'id' => '\d+',
        'format' => '(\.[^/]+)?',
    ]);
```

**Comment by KarelWintersky** [comment]
> Chain of Responsibility

А вот этот термин незнаком уже мне ;-)
